### ISSUE TITLE
Modificar Readme

### ISSUE THREAD

**Issue by albertalvin8080** [albertalvin8080/GCMS-Albert-Sobral#1]
@ramidedantas
[README](https://github.com/AlbertAlvin8080/GCMS-Albert-Sobral/blob/main/README.md)

**Comment by ramidedantas** [comment]
@AlbertAlvin8080 nome adicionado.

Ajustar formatação para ficar como no repositório da turma (títulos, etc.)

**Comment by albertalvin8080** [comment]
Resolvido @ramidedantas

**Comment by ramidedantas** [comment]
Ok @AlbertAlvin8080, pode fechar chamado.
